name: smart-en-system-backend
services:
  - name: backend
    source_dir: /backend
    github:
      repo: dzikrirazzan/turnover_api
      branch: main
      deploy_on_push: true
    run_command: gunicorn --worker-tmp-dir /dev/shm turnover_prediction.wsgi:application
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "${APP_SECRET_KEY}"
        type: SECRET
      - key: ALLOWED_HOSTS
        value: "${APP_DOMAIN},localhost,127.0.0.1"
      - key: POSTGRES_DB
        value: "${DATABASE_NAME}"
      - key: POSTGRES_USER
        value: "${DATABASE_USER}"
      - key: POSTGRES_PASSWORD
        value: "${DATABASE_PASSWORD}"
        type: SECRET
      - key: POSTGRES_HOST
        value: "${DATABASE_HOST}"
      - key: POSTGRES_PORT
        value: "${DATABASE_PORT}"
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:3000"

databases:
  - name: smart-en-db
    engine: PG
    version: "14"
    production: false
    cluster_name: smart-en-cluster

alerts:
  - rule: CPU_UTILIZATION
  - rule: MEM_UTILIZATION
